### ISSUE TITLE
NameError: name 'manga' is not defined

### ISSUE THREAD

**Issue by umarzuki** [jiaweihli/manga_downloader#58]
Ubuntu 14.04 amd64

$ ./manga.py naruto

Which site?
(1) MangaFox
(2) OtakuWorks
(3) MangaReader

Traceback (most recent call last):
  File "./manga.py", line 563, in <module>
    exec('site, manga, chapters, chapters_to_download = parse' + siteDict[site] + '(manga, False, 1)')
  File "<string>", line 1, in <module>
NameError: name 'manga' is not defined

$ ./manga.py naruto

Which site?
(1) MangaFox
(2) OtakuWorks
(3) MangaReader

2
Traceback (most recent call last):
  File "./manga.py", line 563, in <module>
    exec('site, manga, chapters, chapters_to_download = parse' + siteDict[site] + '(manga, False, 1)')
  File "<string>", line 1, in <module>
NameError: name 'manga' is not defined

**Comment by h4xnoodle** [comment]
This is due to the current README only matching what's in master -- not the 0.5.5 release you may have downloaded. 

The code in the release states 
```
[531] '-n' : 'manga = sys.argv[index + 1]',
```
so in the version you're using, you'll need to do `./manga.py -n naruto.
