### ISSUE TITLE
Thread crash

### ISSUE THREAD

**Issue by Tankypon** [jiaweihli/manga_downloader#60]
I always got this issue when I try to retrieve a manga, it's a king of annoying..

Exception in thread Thread-XX:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/tankypon/Nightly/manga_downloader/src/parsers/base.py", line 359, in run
    raise FatalError("Thread crashed while downloading chapter: %s" % str(exception))
FatalError: Thread crashed while downloading chapter: [Errno 104] Connection reset by peer

**Comment by jiaweihli** [comment]
Seems like your internet connection keeps disconnecting.
