### ISSUE TITLE
Changes the working directory to the script location

### ISSUE THREAD

**Issue by kozec** [jiaweihli/manga_downloader#78]
Hello.

[This line](https://github.com/jiaweihli/manga_downloader/blob/master/src/manga.py#L220) changes cwd to whatever directory manga_downloader is installed. I'd guess usual location is somewhere in /usr/lib, or, as in my case, /usr/bin.

I'm not sure why would anyone want to download manga next to his python sources, but even if that is desired, it's gonna crash:

```
Downloading all chapters...
Unable to create download directory. There may be a file 
					with the same name, or you may not have permissions to write 
					there.
Traceback (most recent call last):
  File "/usr/bin/manga_downloader", line 278, in <module>
    main()
  File "/usr/bin/manga_downloader", line 267, in main
    threadPool.append(SiteParserThread(options, None, None))
  File "/usr/share/manga_downloader/parsers/thread.py", line 41, in __init__
    os.makedirs(self.downloadPath)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/bin/something.something/'
```

**Comment by Evolution0** [comment]
Usually you would specify the download location anyway though?

**Comment by kozec** [comment]
Well, I was imagining it would download to current directory, as wget or curl does. But even if there is some other default, it should at least default to something less crash-prone.

**Comment by Evolution0** [comment]
Maybe change the default working directory to the users home?

Something like:
`os.chdir(os.path.expanduser("~"))`

Will default to the users home under both windows and linux.
