### ISSUE TITLE
Only mangapanda works!

### ISSUE THREAD

**Issue by Young-Angelo** [jiaweihli/manga_downloader#95]
When I try to install any manga via sites other than mangapanda,it gives rise to an error:
```
Traceback (most recent call last):
  File "./manga.py", line 297, in <module>
    main()
  File "./manga.py", line 286, in main
    threadPool.append(SiteParserThread(options, None, None))
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/thread.py", line 37, in __init__
    self.siteParser.parseSite()
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/mangafox.py", line 71, in parseSite
    keyword = self.selectFromResults(seriesResults)
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/base.py", line 357, in selectFromResults
    raise self.MangaNotFound('No strict match found. Check query.')
parsers.base.MangaNotFound: Manga not found. No strict match found. Check query
```

**Comment by gromenauer** [comment]
Could you give more info?
Examples (This links works for me):

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.2.2
URL | `https://read.lhtranslation.com/manga-remonster.html`
URL | `https://manganelo.com/manga/read_the_gamer_manga_online_free`

**Comment by Young-Angelo** [comment]
Hi,sorry for the late reply.
(I don't know to create the table,so I am gonna write everything down)

OS :- Ubuntu 18.10(Cosmic)x64
Python :- 3.6.7
Pip3 :-pip 9.0.1 
Npm :- 5.8.0
Manga-py :- lastest
URL :- (I didn't actually type the url,I just used the search builtin)

```
Traceback (most recent call last):
  File "./manga.py", line 297, in <module>
    main()
  File "./manga.py", line 286, in main
    threadPool.append(SiteParserThread(options, None, None))
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/thread.py", line 37, in __init__
    self.siteParser.parseSite()
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/mangafox.py", line 71, in parseSite
    keyword = self.selectFromResults(seriesResults)
  File "/home/kamehameha/Documents/manga_downloader-master/src/parsers/base.py", line 357, in selectFromResults
    raise self.MangaNotFound('No strict match found. Check query.')
parsers.base.MangaNotFound: Manga not found. No strict match found. Check query.
```

**Comment by gromenauer** [comment]
Ooops!
I thought that I was answering in another repo, sorry.

**Comment by sparky1088** [comment]
Ok so i can say for sure that not only one site works as I have gotten a few of them to work correctly. I will say that I do think the scripts need to be checked/updated for the domains as I believe some of them have changed. I also have had trouble with certain series. Some things to keep in mind: its a best match type thing. In order to get a manga with more than 1 word in its name you have to use "" (eg `python manga.py "one piece"`)

Some other things I've noticed is that sometimes it returns with the manga but 0 chapters found. I think this has to do with how some sites have moved but I am unsure. eg searching for "chibi vampire" at batato results in this but you get a different error at mangafox but it works on mangareader if you use the name karin instead, but chibi vampire fails (it also doesn't have the last 3 volumes I think). I am not sure why this is unless it has to do with the domains having moved. It has been a while. I don't know enough python to go fix it otherwise I would attempt to do so.

Good luck. hopefully this helps or hopefully someone comes along and fixes the code base.

**Comment by Evolution0** [comment]
Yes a lot is based on how much the site layout has changed due to how scraping works, it hasn't been updated in more than 2 years, its not surprising that a lot is broken. Heck it would be more strange if it still worked.

I actually added Mangapanda to [another parser library](https://github.com/nhanb/fundoshi) back in 2017 myself and I can't even guarantee that it works anymore, its the nature of the thing.

It seems people use [FMD](https://github.com/riderkick/FMD) these days.
